sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        VXcJDvei/2co/MWJfVLodTLVV8Ll7axfsyWiMHCVHX2HZy4NDsKiqFNWP3RTTbYsGMr5W95cylO2hYc7m9HrpFLgOnxEWvVSO6CxHqw3Gg4M2DaEbl/yCirmE6kOkuoB1M9xu0ZCW4iiDU1iZmh70KIuoz9grKmf0ce+3aYDsaKZpqKHEcXg/ZM0fKqAGqw80qHZN8vIy3ul80f32lDZazONbwSOrVOxIRat5MOCja7S5pxN8cJyG5vBDKgyKFMhyEuQJZnmH2kq8PU/WzGGvysObP9VomnSvEZHgz1Bgt0Ao7MXwI6hEjbQfg6+A3wt2ts0m+zsjUNVda+JGyDM8cEEwbzU1QfezJBjtAwbRW8PiV2sRhfDafv7Tx96RPdBUq13UUPq4I5YrKTg3XNHakBd7aPrUBwrdzI4k5iM+DpTmquL+wi0pdT+y33o85lWgfizcyEvGs4jqvbeHGFi+MwKbW57Zg00AH0CxGbqv+dfLRn8b7SZHpudlQLejQ0e+zFWgjJYzmzk6hDkIAgAMp4vv79SIbGOP7Epwj3gv7UxUWho9Q+1p/gjsggLMPxFW6V/S9cRnjMF44PLyT20vAyAeMxF3flfBxdYliExhARgMjkJOS84wgTIGa7yvR8iHEnkPHg9dQ0LnodcBN88ZrM8xLXtFFWQoZNqgaw4o5U=
    - secure: >-
        SHqFJAVfy2vvC2w1eir181xShhLlXMJeZt6B11Madhp9fDg9JRZ+rBM8aBP5Nwji9ZA+TBSg9NEOMIJGGEiq7hxRtKBotqWsisR3C5+1GSRaYfsJ24O0RU6lwXN6OgO0rG7ZYt8yPlfZib2Ab18FDn91RlMekCa/IVHykJQo8EaqjfvyntxLc/aEp4Ynt3xdD2d+IBFVjWMLt3nRWEzwfxJVRLXbASZ2M7hvM+LKFbJ5D7h24HF1MpiiHkZJ71xCntUI4v0p3gAd5aKB/MNyNvJ5SVQ3rXbDg/AE0LdLpK32lkPKidS8rDEZyo1EqMrR9tqow7Ps0BklordmSq/yPLL4oKlBPOX+yxe6DROjQnCJsZRr0x1HmqVX1kjhH4qnQB0peGd2Jv0X4G2qIKSfx4f/77/qNqpICW2vpXGFBzqwWBXGBJLrCaUrvgzp0tA/uhr6AotqKqWzH9r9HfjuFHvfIRRXGqMjWBzY40FvFR64cQi8I/oBPTiRhwkOpOGDrlrGucKp4lRAfKvc4bIrFiqHWTkL4gai/SBM3oYjD68d9sB7QZ0sTPDuXB1Py/4UYNWmbWxwIMvqn7rALYIaScq0/qRVpoMdgPVWGuJ2iOSgRUHt+aRo0W7KXKz5bK9a7Uk5R1+gK1junZOKXqevAd9Wvm3n1xeaMLl6vrzsq+k=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
